// ts/lazy-loading-app/src/components/LazyLoading.vue
<script setup>
import { onMounted, ref } from 'vue'
import AppearTransition from './Transitions/AppearTransition.vue'

const rootElement = ref(null)
const renderComponent = ref(false)

onMounted(() => {
    if (rootElement.value) {
        createIntersectionObserver().observe(rootElement.value)
    }
})

function createIntersectionObserver() {
    return new IntersectionObserver(entries => {
        for (const entry of entries) {
            if (entry.isIntersecting) {
                renderComponent.value = true
            }
        }
    })
}
</script>

<template>
    <div ref="rootElement">
        <AppearTransition>
            <slot v-if="renderComponent" />
        </AppearTransition>
    </div>
</template>

// svelte/lazyloading/src/lib/LazyLoading.svelte
<script>
    import { onMount } from 'svelte'
    import { fade } from 'svelte/transition'

    let rootElement = null
    let renderComponent = false

    onMount(() => {
        if (rootElement) {
            createIntersectionObserver().observe(rootElement)
        }
    })

    const createIntersectionObserver = () => {
        return new IntersectionObserver(entries => {
            for (const entry of entries) {
                if (entry.isIntersecting) {
                    renderComponent = true
                }
            }
        })
    }
</script>

<div bind:this={rootElement}>
    {#if renderComponent}
        <div transition:fade>
            <slot></slot>
        </div>
    {/if}
</div>
