// languages/svelte/notes/src/templates/FormButton.svelte
<script lang=ts>
    import {createEventDispatcher} from 'svelte'

    export let type: 'submit' | 'button'
    export let color: string

    const dispatch = createEventDispatcher()
</script>

<button
    type={type}
    class="w-full p-2 text-white rounded-md transition-colors {color}"
    on:click={() => dispatch('clicked')}
>
    <slot />
</button>

// vue/notes/src/components/FormButton.vue
<script setup lang="ts">
type Props = {
    type: 'submit' | 'button'
    color: string
}

const { type, color } = defineProps<Props>()
</script>

<template>
    <button
        :type="type"
        class="w-full p-2 text-white rounded-md transition-colors"
        :class="color"
        @click="$emit('clicked')"
    >
        <slot />
    </button>
</template>
